# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0fe97d2ac52d461394d30e1e982bec0bb11c54ab57c10014e751c3ccad20fd14e89be680d0934c7b8bd501d8f8152bf8a7275ed4a4bc09cd9aaf44f69cc308ab

test:
  secret_key_base: 59dae01f642cbaa7ef1a65350e700796550892c31139b0afbd9d0d2aa5f58b39141af7fddc60870fdb00cfc5dd5f0974c0b64480f71c3d10bb8abf6653b56618

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
